package bean;
// Generated 2017-5-25 10:33:00 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * AdminInfo generated by hbm2java
 */
public class Adminuser implements java.io.Serializable {

	private String adminId;
	private String password;
	private String name;
	private String phone;
	private Set worksInfos = new HashSet(0);
	private Set newses = new HashSet(0);

	public Adminuser() {
	}

	public Adminuser(String adminId, String password, String name, String phone) {
		this.adminId = adminId;
		this.password = password;
		this.name = name;
		this.phone = phone;
	}

	public Adminuser(String adminId, String password, String name, String phone, Set worksInfos, Set newses) {
		this.adminId = adminId;
		this.password = password;
		this.name = name;
		this.phone = phone;
		this.worksInfos = worksInfos;
		this.newses = newses;
	}

	public String getAdminId() {
		return this.adminId;
	}

	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getWorksInfos() {
		return this.worksInfos;
	}

	public void setWorksInfos(Set worksInfos) {
		this.worksInfos = worksInfos;
	}

	public Set getNewses() {
		return this.newses;
	}

	public void setNewses(Set newses) {
		this.newses = newses;
	}

}
