package bean;
// Generated 2017-5-25 10:33:00 by Hibernate Tools 3.5.0.Final

/**
 * LoginInfo generated by hbm2java
 */
public class LoginInfo implements java.io.Serializable {

	private LoginInfoId id;
	private String userId,password;

	/**
	 * @return the userId
	 */
	public String getUserId() {
		return id.getUserId();
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return id.getPassword();
	}

	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	public LoginInfo() {
	}

	public LoginInfo(LoginInfoId id) {
		this.id = id;
	}

	public LoginInfoId getId() {
		return this.id;
	}

	public void setId(LoginInfoId id) {
		this.id = id;
	}

}
