package bean;
// Generated 2017-5-24 16:53:17 by Hibernate Tools 3.5.0.Final

/**
 * LoginInfo generated by hbm2java
 */
public class LoginInfo implements java.io.Serializable {

	private LoginInfoId id;

	public LoginInfo() {
	}

	public LoginInfo(LoginInfoId id) {
		this.id = id;
	}

	public LoginInfoId getId() {
		return this.id;
	}

	public void setId(LoginInfoId id) {
		this.id = id;
	}

}
