package bean;
// Generated 2017-5-24 16:53:17 by Hibernate Tools 3.5.0.Final

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Integer newsId;
	private AdminInfo adminInfo;
	private String content;

	public News() {
	}

	public News(AdminInfo adminInfo, String content) {
		this.adminInfo = adminInfo;
		this.content = content;
	}

	public Integer getNewsId() {
		return this.newsId;
	}

	public void setNewsId(Integer newsId) {
		this.newsId = newsId;
	}

	public AdminInfo getAdminInfo() {
		return this.adminInfo;
	}

	public void setAdminInfo(AdminInfo adminInfo) {
		this.adminInfo = adminInfo;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
