package bean;
// Generated 2017-5-27 17:44:09 by Hibernate Tools 3.5.0.Final

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Integer newsId;
	private Adminuser adminuser;
	private String content;

	public News() {
	}

	public News(Adminuser adminuser, String content) {
		this.adminuser = adminuser;
		this.content = content;
	}

	public Integer getNewsId() {
		return this.newsId;
	}

	public void setNewsId(Integer newsId) {
		this.newsId = newsId;
	}

	public Adminuser getAdminuser() {
		return this.adminuser;
	}

	public void setAdminuser(Adminuser adminuser) {
		this.adminuser = adminuser;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
