package bean;
// Generated 2017-5-24 16:53:17 by Hibernate Tools 3.5.0.Final

/**
 * Teaminfo generated by hbm2java
 */
public class Teaminfo implements java.io.Serializable {

	private TeaminfoId id;

	public Teaminfo() {
	}

	public Teaminfo(TeaminfoId id) {
		this.id = id;
	}

	public TeaminfoId getId() {
		return this.id;
	}

	public void setId(TeaminfoId id) {
		this.id = id;
	}

}
